### ISSUE TITLE
[BUG] stats list after a sort causes a panic

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#1502]
# Description
Running a query like `... | sort colA | stats list(colA)` causes a panic. For example, 
```
country=Pitcairn AND weekday=Monday | sort app_version | stats list(app_version)
```
Without the `sort`, it doesn't panic.

Here's part of the panic output:
```
panic: interface conversion: interface {} is []string, not int64

goroutine 81 [running]:
github.com/siglens/siglens/pkg/segment/search.PerformMeasureAggsOnRecs.func1()
        /home/andrew/sigscalr/hyperion/siglens/pkg/segment/search/searchaggs.go:638 +0x355
github.com/siglens/siglens/pkg/segment/search.PerformMeasureAggsOnRecs(0xc024e2a000, 0xc00939bec0, 0xc024cf7018, 0xc024cf7018?, 0x1, 0x0)
        /home/andrew/sigscalr/hyperion/siglens/pkg/segment/search/searchaggs.go:653 +0x667
github.com/siglens/siglens/pkg/segment/search.PerformAggsOnRecs(0xc024e2a000?, 0xc024a28300?, 0xc00939bec0?, 0x6?, 0xc00939a390?, 0x0?, 0x2?)
        /home/andrew/sigscalr/hyperion/siglens/pkg/segment/search/searchaggs.go:362 +0x54
```

# Steps to Reproduce
Give detailed step-by-step instructions to help us easily reproduce the issue.
1. ...

# Expected Behavior
Should not panic; should give the same results as without the `sort` but with the multivalue list elements sorted

# Environment
- Commit Hash: 9ea9a4a

**Comment by sathkrith** [comment]
I'll be working on this
