### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dongbin86** [siglens/siglens#674]
# Description
Clearly describe the bug and how to reproduce it. If applicable, include screenshots.
INFO[2024-03-26 11:11:54] ----- Siglens server type SingleNode starting up -----  
INFO[2024-03-26 11:11:54] ----- Siglens Ingestion server starting on 0.0.0.0:8081 -----  
INFO[2024-03-26 11:11:54] ----- Siglens Query server starting on 0.0.0.0:5122 -----  
INFO[2024-03-26 11:11:54] ----- Siglens UI starting on 0.0.0.0:5122 -----  
panic: runtime error: slice bounds out of range [:2000033] with length 2000000

goroutine 2736 [running]:
github.com/siglens/siglens/pkg/segment/writer.(*SegStore).encodeSingleString(0xc000732000, {0xc0158c1d90, 0x7}, {0xc01588e900, 0x31}, 0x0, 0x0?, 0x0?)
        /home/hongshen/sourcecode/siglens-develop/pkg/segment/writer/packer.go:463 +0x6ec
github.com/siglens/siglens/pkg/segment/writer.(*SegStore).encodeRawJsonObject.func1({0xc015914031?, 0x48167e?, 0x1638240?}, {0xc01591403c, 0x31, 0x31}, 0x1, 0x380?)
        /home/hongshen/sourcecode/siglens-develop/pkg/segment/writer/packer.go:138 +0x595
github.com/buger/jsonparser.ObjectEach({0xc01591402e, 0x14b, 0xfd2}, 0xc00fc7d1e0, {0x0?, 0xc01467a000?, 0x0?})
        /home/hongshen/go/pkg/mod/github.com/buger/jsonparser@v1.1.1/parser.go:1128 +0x46f
github.com/siglens/siglens/pkg/segment/writer.(*SegStore).encodeRawJsonObject(0x18e7913d9c5?, {0x0?, 0x4fef27?}, {0xc01591402e?, 0xc00fc7d248?, 0xc00fc7d2c8?}, 0x0, 0x41beba?, 0x0, 0x2)
        /home/hongshen/sourcecode/siglens-develop/pkg/segment/writer/packer.go:172 +0xb1
github.com/siglens/siglens/pkg/segment/writer.(*SegStore).EncodeColumns(0xc000732000, {0xc01591402e, 0x14b, 0xfd2}, 0x100000000203005?, 0xc01591402e?, 0x0?)
        /home/hongshen/sourcecode/siglens-develop/pkg/segment/writer/packer.go:80 +0xa5
github.com/siglens/siglens/pkg/segment/writer.(*SegStore).WritePackedRecord(0xc000732000, {0xc01591402e, 0x14b, 0xc0158c1d80?}, 0x10?, 0x0?)
        /home/hongshen/sourcecode/siglens-develop/pkg/segment/writer/segstore.go:835 +0x87
github.com/siglens/siglens/pkg/segment/writer.AddEntryToInMemBuf({0xc0158d5c98, 0x18}, {0xc01591402e, 0x14b, 0xfd2}, 0x18e7913d9c5, {0xc0158c1d80?, 0x1404eb8?}, 0x14b, 0x0, ...)
        /home/hongshen/sourcecode/siglens-develop/pkg/segment/writer/segwriter.go:257 +0x365
github.com/siglens/siglens/pkg/es/writer.ProcessIndexRequest({0xc01591402e, 0x14b, 0xfd2}, 0x18e7913d9c5, {0xc0158c1d80?, 0xc00092e840?}, 0x7017053c7fff?, 0x40?, 0xc015832fe0?, 0x0)
        /home/hongshen/sourcecode/siglens-develop/pkg/es/writer/esBulkHandler.go:279 +0x191
github.com/siglens/siglens/pkg/es/writer.HandleBulkBody({0xc002d42000, 0xd5d, 0x80000}, 0xc000220780?, 0x1?, 0x14b2cf0)
        /home/hongshen/sourcecode/siglens-develop/pkg/es/writer/esBulkHandler.go:130 +0x430
github.com/siglens/siglens/pkg/es/writer.ProcessBulkRequest(0xc00090ac00, 0x1644608?, 0xc000044088?)
        /home/hongshen/sourcecode/siglens-develop/pkg/es/writer/esBulkHandler.go:61 +0x45
github.com/siglens/siglens/pkg/server/ingest.esPostBulkHandler.func1(0xd?)
        /home/hongshen/sourcecode/siglens-develop/pkg/server/ingest/entryHandlers.go:49 +0x77
github.com/siglens/siglens/pkg/server/ingest.(*ingestionServerCfg).Recovery.func1(0xc0003ba6e0?)
        /home/hongshen/sourcecode/siglens-develop/pkg/server/ingest/middleware.go:34 +0x4b
github.com/fasthttp/router.(*Router).Handler(0xc0001f4460, 0xc00090ac00)
        /home/hongshen/go/pkg/mod/github.com/fasthttp/router@v1.4.1/router.go:414 +0x46a
github.com/siglens/siglens/pkg/server/ingest.cors.func1(0xc00090ac00)
        /home/hongshen/sourcecode/siglens-develop/pkg/server/ingest/server.go:212 +0xd5
github.com/valyala/fasthttp.(*Server).serveConn(0xc000016000, {0x1649f98?, 0xc0023bcda0})
        /home/hongshen/go/pkg/mod/github.com/valyala/fasthttp@v1.45.0/server.go:2371 +0x11f5
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000224000, 0xc0000a54a0)
        /home/hongshen/go/pkg/mod/github.com/valyala/fasthttp@v1.45.0/workerpool.go:224 +0xa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
        /home/hongshen/go/pkg/mod/github.com/valyala/fasthttp@v1.45.0/workerpool.go:196 +0x38
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /home/hongshen/go/pkg/mod/github.com/valyala/fasthttp@v1.45.0/workerpool.go:195 +0x1b0
exit status 2
![Uploading 搜狗截图20240326125431.png…]()

# Steps to Reproduce
Give detailed step-by-step instructions to help us easily reproduce the issue.
1. ...

# Expected Behavior
Clearly describe what you expect to happen.

# Environment
- Commit Hash: [e.g. 9ed5f0a]
- OS: [e.g. MacOS 14.1.1 on apple silicon]
- Browser and Version (if applicable): [e.g. chrome 119.0.6045.159 arm64, safari 19616.2.9.11.7]

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by nkunal** [comment]
Hi @dongbin86 can you describe what kind of data and how much data were you sending to make this happen?

**Comment by dongbin86** [comment]
Sorry, I forgot how much data was written at that time, but it did happen, and I can't reproduce it.

**Comment by vinhjaxt** [comment]
Same here
